---
# Source: mounica/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-mounica
  labels:
    helm.sh/chart: mounica-0.1.0
    app.kubernetes.io/name: mounica
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: mounica/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-mounica
  labels:
    helm.sh/chart: mounica-0.1.0
    app.kubernetes.io/name: mounica
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mounica
    app.kubernetes.io/instance: release-name
---
# Source: mounica/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-mounica
  labels:
    helm.sh/chart: mounica-0.1.0
    app.kubernetes.io/name: mounica
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: mounica
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: mounica-0.1.0
        app.kubernetes.io/name: mounica
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-mounica
      containers:
        - name: mounica
          image: "pathidocker/javawebapp:38"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: mounica/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-mounica-test-connection"
  labels:
    helm.sh/chart: mounica-0.1.0
    app.kubernetes.io/name: mounica
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-mounica:80']
  restartPolicy: Never
